#!/bin/bash
#
# script 	rs-backup
# purpose	make backups from ec2-instance into a S3 bucket, using wordpress 
# 			backup ad database backup commands.
# needs		wp-cli
#			aws-cli
# app		doc, webapp
# environments	prod (scheduled via cron), test & dev (only run when needed)
# runas		ec2-user
# location	remote: github
#			local: /usr/local/bin
# created	12-5-2017
# author	rs
#
# 
cd /var/www/html/wordpress || { echo "Error: wordpress directory not found"; exit 1 ; }
mkdir /tmp/rsbackup || { echo "Could not create /tmp/rsbackup directory"; exit 1 ; }
sudo /usr/local/bin/wp db export /tmp/rsbackup/docserver-data.$(date +"%Y%m%d_%H
%M%S") || { echo "Could not create wordpress database export with wp db export"; exit 1 ; }
sudo tar -vczf /tmp/rsbackup/docserver-file.$(date +"%Y%m%d_%H%M%S") .
## Transfer files to s3

aws s3 sync /tmp/rsbackup s3://thirty-zero-devops || { echo "Could not connect to s3"; exit 1 ; }
rm -rf /tmp/rsbackup/*
